### ISSUE TITLE
Problems running pmc_core debugging

### ISSUE THREAD

**Issue by kowalej** [intel/S0ixSelftestTool#3]
When first running the tool, I encountered errors running the `s0ix-selftest-tool.sh` script relating to line 1446:
`echo $i >$PMC_CORE_SYSFS_PATH/ltr_ignore 2>&1`

this resolved on my system to writes to `/sys/kernel/debug/pmc_core/ltr_ignore`
I was receiving "Operation not permitted", whether running as root or otherwise.

After some digging around, I found that I needed to disable secure boot in my BIOS settings to get this working.

Perhaps a warning could be added to the script itself or the common issues section in the README.

**Comment by qwang59** [comment]
Thanks for trying the script, I will add in the README, in my test environment, I've never enable the secure boot options in BIOS, so I did not notice this issue, thanks for point me it!
